#define om if
#define annars else
#define namnplats namespace
#define använd using
#define nummer int
#define huvud main
#define kut cout
#define slutr endl
#define returnera return
#define kin cin
#define sträng string
#define boolesk bool
#define lång long
#define tom void
#define kosinus cos
#define för for
#define förvarje foreach
#define medans while
#define gör do
#define förskök try
#define fånga catch
#define konstant const
#define tecken char
